import Link from 'next/link';

export const metadata = {
  title: 'Terms of Service — Chat to Website',
  description: 'Terms of Service for Chat to Website by The Yencee Labs',
};

export default function TermsPage() {
  return (
    <main className="min-h-screen bg-white">
      <nav className="border-b border-gray-200">
        <div className="max-w-3xl mx-auto px-6 py-4">
          <Link href="/" className="font-semibold text-black hover:opacity-70 transition">
            ← Chat to Website
          </Link>
        </div>
      </nav>

      <article className="max-w-3xl mx-auto px-6 py-16">
        <header className="mb-12">
          <h1 className="text-4xl font-semibold text-black mb-4">Terms of Service</h1>
          <p className="text-gray-500">Effective Date: February 2026</p>
        </header>

        <div className="prose prose-gray max-w-none text-gray-600 space-y-8">
          <p>
            Welcome to Chat to Website. By using our service, you agree to these Terms of Service.
          </p>

          <section>
            <h2 className="text-2xl font-semibold text-black mb-4">1. Service Description</h2>
            <p>
              Chat to Website allows you to create and deploy websites by describing them through 
              Telegram or our web interface. Websites are generated using AI and hosted on Vercel.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-black mb-4">2. Account & Credits</h2>
            <ul className="list-disc pl-6 space-y-2">
              <li>Each user receives 1 free website and 20 updates</li>
              <li>Additional credits can be purchased</li>
              <li>Credits do not expire</li>
              <li>Credits are non-transferable</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-black mb-4">3. Acceptable Use</h2>
            <p>You agree NOT to create websites that:</p>
            <ul className="list-disc pl-6 space-y-2 mt-2">
              <li>Contain illegal content</li>
              <li>Infringe intellectual property rights</li>
              <li>Spread malware or phishing</li>
              <li>Promote hate speech or violence</li>
              <li>Violate any applicable laws</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-black mb-4">4. Content Ownership</h2>
            <p>
              <strong>Your Content:</strong> You retain ownership of your website content. 
              By using our service, you grant us a license to host and display your content.
            </p>
            <p className="mt-2">
              <strong>Generated Code:</strong> The HTML/CSS/JS generated for your website 
              is licensed to you for use. You may export and host it elsewhere.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-black mb-4">5. AI-Generated Content</h2>
            <p>
              Content is generated by AI and may not always be perfect. You are responsible 
              for reviewing and editing your website before publishing.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-black mb-4">6. Website Hosting</h2>
            <ul className="list-disc pl-6 space-y-2">
              <li>Websites are hosted on Vercel infrastructure</li>
              <li>We do not guarantee 100% uptime</li>
              <li>Custom domains may be added (future feature)</li>
              <li>We may remove websites violating these terms</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-black mb-4">7. Limitation of Liability</h2>
            <p>
              THE SERVICE IS PROVIDED "AS IS" WITHOUT WARRANTIES. WE ARE NOT LIABLE FOR ANY 
              INDIRECT, INCIDENTAL, OR CONSEQUENTIAL DAMAGES ARISING FROM YOUR USE OF THE SERVICE.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-black mb-4">8. Termination</h2>
            <p>
              We may terminate your access for violation of these terms. Upon termination, 
              your websites may be removed from our hosting.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-black mb-4">9. Governing Law</h2>
            <p>These Terms are governed by the laws of India.</p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-black mb-4">10. Contact</h2>
            <p>
              Questions? Contact us at:{' '}
              <a href="mailto:legal@yenceelabs.com" className="text-black underline">
                legal@yenceelabs.com
              </a>
            </p>
          </section>
        </div>
      </article>

      <footer className="border-t border-gray-200 py-8">
        <div className="max-w-3xl mx-auto px-6 text-center text-sm text-gray-500">
          <div className="flex justify-center gap-6 mb-4">
            <Link href="/privacy" className="hover:text-black transition">Privacy</Link>
            <Link href="/terms" className="hover:text-black transition">Terms</Link>
            <Link href="/refund" className="hover:text-black transition">Refunds</Link>
          </div>
          <p>© {new Date().getFullYear()} The Yencee Labs. All rights reserved.</p>
        </div>
      </footer>
    </main>
  );
}
